<h3>Deskero</h3>
<ul class="tabs">
    
    <li>
        <a href="<?php echo $this->getUrl('adminhtml/system_config/edit/section/deskero_settings'); ?>" class="tab-item-link">
            <span><?php echo $this->__('Settings'); ?></span>
        </a>
    </li>
    
    <li>
        <a href="<?php echo $this->getUrl('*/*/launch'); ?>" target="_blank" class="tab-item-link">
            <span><?php echo $this->__('Launch Deskero'); ?></span>
        </a>
    </li>
    
    <li>
        <a href="<?php echo $this->getUrl('*/*/createTicket'); ?>" class="tab-item-link active">
            <span><?php echo $this->__('Create Ticket'); ?></span>
        </a>
    </li>
    
</ul>